#!/usr/bin/env python3
"""
postprocess.py — cleans up HTML after wget.

usage: python postprocess.py <OUTPUT_DIR> <ORIGIN_HOST>

- Renames files with @ generated by wget (replacement for ? in query strings).
- Removes residual absolute references to the origin host.
- Strips CMS-specific tags (WordPress emoji, REST links, oEmbed, generator meta).
"""

import pathlib
import re
import sys
from urllib.parse import urljoin

# @ preceded by a file extension and followed by param=value → came from ?querystring
_QUERY_AT = re.compile(r"@[^@=]*=")


def normalize_query_string_files(output_dir: pathlib.Path) -> list[tuple[str, str]]:
    """
    Renames files where wget replaced ? in query strings with @.

    Example: style.css@ver=6.4.1 → style.css
             script.js@ver=1.2&m=1 → script.js

    Returns a list of (original_name, clean_name) for updating references in text
    files. When two files map to the same clean name, the first (alphabetical order)
    wins and the duplicate is discarded.
    """
    renames: list[tuple[str, str]] = []
    seen_clean: set[pathlib.Path] = set()

    for path in sorted(output_dir.rglob("*")):
        if not path.is_file() or not _QUERY_AT.search(path.name):
            continue

        clean_name = path.name.split("@")[0]
        if not clean_name:
            continue

        clean_path = path.parent / clean_name

        if clean_path in seen_clean or clean_path.exists():
            path.unlink()
        else:
            path.rename(clean_path)
            seen_clean.add(clean_path)

        renames.append((path.name, clean_name))

    return renames


def apply_renames_to_text_files(output_dir: pathlib.Path, renames: list[tuple[str, str]]) -> None:
    """Replaces references to renamed files in all HTML/CSS/JS files."""
    if not renames:
        return

    text_exts = {".html", ".htm", ".css", ".js"}
    for text_file in output_dir.rglob("*"):
        if not text_file.is_file() or text_file.suffix.lower() not in text_exts:
            continue
        try:
            text = text_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue

        modified = text
        for old_name, clean_name in renames:
            modified = modified.replace(old_name, clean_name)
            # Without --convert-links, HTML keeps the original ?-form (e.g. style.css?ver=6.4.1)
            # while the file on disk uses @ (style.css@ver=6.4.1). Replace both forms.
            q_version = old_name.replace("@", "?", 1)
            if q_version != old_name:
                modified = modified.replace(q_version, clean_name)

        if modified != text:
            text_file.write_text(modified, encoding="utf-8")


def build_patterns(origin_host: str, extra_hosts: list[str] | None = None):
    host_patterns = [
        # any http/https://<host> → relative URL (origin + extra CDNs)
        (re.compile(rf"https?://{re.escape(h)}"), "")
        for h in [origin_host] + (extra_hosts or [])
    ]
    return host_patterns + [
        # WordPress emoji script (dead weight on static sites)
        (
            re.compile(
                r"<script[^>]*>\s*window\._wpemojiSettings.*?</script>",
                re.IGNORECASE | re.DOTALL,
            ),
            "",
        ),
        (
            re.compile(r"<link[^>]*wp-emoji[^>]*>", re.IGNORECASE),
            "",
        ),
        # WordPress REST/oEmbed/EditURI links
        (
            re.compile(
                r'<link[^>]+rel=["\'](?:https://api\.w\.org/|alternate|EditURI|wlwmanifest)[^>]*>',
                re.IGNORECASE,
            ),
            "",
        ),
        # WordPress generator meta tag (exposes version info)
        (
            re.compile(r'<meta[^>]*name=["\']generator["\'][^>]*>', re.IGNORECASE),
            "",
        ),
        # WordPress pingback link
        (
            re.compile(r'<link[^>]+rel=["\']pingback["\'][^>]*>', re.IGNORECASE),
            "",
        ),
    ]


def absolutize_html_urls(text: str, html_path: pathlib.Path, output_dir: pathlib.Path) -> str:
    """Converts relative href/src/srcset paths (../../, ../) to absolute (/path)."""
    parts = html_path.relative_to(output_dir).parent.parts
    base_url = "/" + "/".join(parts) + "/" if parts else "/"

    def is_absolute(url: str) -> bool:
        return url.startswith(("http", "https", "//", "#", "data:", "javascript:", "/"))

    def resolve(url: str) -> str:
        return url if is_absolute(url) else urljoin(base_url, url)

    def fix_chunk(chunk: str) -> str:
        """Rewrite relative URLs in href/src/srcset attributes to absolute paths."""
        # href="..." and src="..."
        chunk = re.sub(
            r'((?:href|src)=)(["\'])([^"\']+)\2',
            lambda m: f'{m.group(1)}{m.group(2)}{resolve(m.group(3))}{m.group(2)}',
            chunk,
            flags=re.IGNORECASE,
        )

        # srcset="url1 w1, url2 w2, ..."
        def fix_srcset(m: re.Match) -> str:
            q = m.group(1)
            entries = []
            for entry in m.group(2).split(","):
                tokens = entry.strip().split()
                if tokens:
                    tokens[0] = resolve(tokens[0])
                entries.append(" ".join(tokens))
            return f'srcset={q}{", ".join(entries)}{q}'

        chunk = re.sub(r'srcset=(["\'])([^"\']+)\1', fix_srcset, chunk, flags=re.IGNORECASE)

        # Internal links ending in /index.html → strip to /
        chunk = re.sub(
            r'((?:href|src)=["\'])(/[^"\']*/)index\.html(["\'])',
            r'\1\2\3',
            chunk,
            flags=re.IGNORECASE,
        )

        return chunk

    # Split on <script> blocks so JS string contents (e.g. template literals with
    # href="${expr}") are not mistaken for relative HTML attribute URLs.
    segments = re.split(r'(<script[\s\S]*?</script>)', text, flags=re.IGNORECASE)
    return "".join(fix_chunk(part) if i % 2 == 0 else part for i, part in enumerate(segments))


def main():
    if len(sys.argv) < 3:
        print("usage: postprocess.py <OUTPUT_DIR> <ORIGIN_HOST> [<CDN_HOST> ...]", file=sys.stderr)
        sys.exit(2)

    output_dir = pathlib.Path(sys.argv[1])
    origin_host = sys.argv[2]
    extra_hosts = sys.argv[3:]  # extra CDN domains whose absolute URLs will also be stripped

    if not output_dir.is_dir():
        print(f"directory does not exist: {output_dir}", file=sys.stderr)
        sys.exit(2)

    if extra_hosts:
        print(f"[postprocess] stripping URLs from {len(extra_hosts)} extra CDN(s): {', '.join(extra_hosts)}")

    # Step 1: normalize filenames with @ (wget's replacement for ? in query strings)
    renames = normalize_query_string_files(output_dir)
    if renames:
        apply_renames_to_text_files(output_dir, renames)
        print(f"[postprocess] {len(renames)} query-string file(s) renamed")
        for old, new in renames:
            print(f"[postprocess]   {old} → {new}")

    # Step 2: strip absolute URLs and CMS artifacts from HTML files
    patterns = build_patterns(origin_host, extra_hosts)
    count = 0

    for html in output_dir.rglob("*.html"):
        try:
            text = html.read_text(encoding="utf-8", errors="ignore")
        except Exception as e:
            print(f"[postprocess] error reading {html}: {e}", file=sys.stderr)
            continue

        original = text
        for pat, repl in patterns:
            text = pat.sub(repl, text)
        text = absolutize_html_urls(text, html, output_dir)

        if text != original:
            html.write_text(text, encoding="utf-8")
            count += 1
            print(f"[postprocess] cleaned: {html}")

    print(f"[postprocess] {count} file(s) modified")


if __name__ == "__main__":
    main()
